spring.application.name=reserva-sala-reuniao

# Configuração de Conexão com o Banco de Dados MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db_reserva_salas?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Força o Hibernate a limpar e recriar as tabelas do zero a cada inicialização
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Ativa o suporte para rodar scripts SQL personalizados na inicialização
spring.sql.init.mode=always

# Configuração do Resend para envio de email
resend.api.key=colar_chave_presente_relatorio
resend.email.remetente=onboarding@resend.dev